name: pr-validation
on:
 pull_request:
   types:
     - opened
     - synchronize
 push:
    branches:
      - develop
jobs:
 pr-validation0job:
    runs-on: ubuntu-latest
    steps:
      - name: welome steps
        run: echo "welcome to github actions"
      - name: second step
        run: echo "second step run"